### ISSUE TITLE
Release 1.0 Questions

### ISSUE THREAD

**Issue by dominik-bln** [davebelais/gtin#4]
I have a few quick questions regarding the recent 1.0 release:

Is it on purpose that the version number on PyPI is ["1.0.1631641032"](https://pypi.org/project/gtin/1.0.1631641032/)?

Could you elaborate on what the breaking changes are or point me to a changelog somewhere?

Thank you.

**Comment by davebelais** [comment]
Hi @dominik-bln - 

a) Yes. Micro version increments are released automatically in response to changes in the [GCP Prefix Format List](https://www.gs1.org/docs/gcp_length/gcpprefixformatlist.xml). The micro version is a timestamp derived from that spec. See [scripts/update_gcp_prefix_format_list.py](https://github.com/enorganic/gtin/blob/master/scripts/update_gcp_prefix_format_list.py). 
b) The breaking change is dropping python 2 support.

**Comment by dominik-bln** [comment]
Thank you for the quick response.
